[build]
  command = "CI='' pnpm install && pnpm --filter @bsi/web build"
  publish = "packages/web/.next"
  [build.environment]
    NODE_VERSION = "20"
    NPM_FLAGS = "--legacy-peer-deps"
    CI = ""

[context.production]
  command = "CI='' pnpm install && pnpm --filter @bsi/web build"
  publish = "packages/web/.next"

[context.deploy-preview]
  command = "CI='' pnpm install && pnpm --filter @bsi/web build"
  publish = "packages/web/.next"

[context.branch-deploy]
  command = "CI='' pnpm install && pnpm --filter @bsi/web build"
  publish = "packages/web/.next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
